# Generated by Django 4.2.4 on 2023-09-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bufo',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BufoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bufo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bufo_vote_set', to='viewer.bufo')),
            ],
        ),
    ]
