// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbufo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ViewerBufo struct {
	Name    string
	Created pgtype.Timestamptz
}

type ViewerBufovote struct {
	ID      int64
	Value   int32
	Created pgtype.Timestamptz
	BufoID  string
}
