// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package dbufo

import (
	"context"
	"database/sql"
	"time"
)

const createBufo = `-- name: CreateBufo :one
insert into
    viewer_bufo (name, created)
values
    (?, ?)
on conflict(name) do nothing
returning name, created
`

type CreateBufoParams struct {
	Name    string
	Created time.Time
}

func (q *Queries) CreateBufo(ctx context.Context, arg CreateBufoParams) (ViewerBufo, error) {
	row := q.db.QueryRowContext(ctx, createBufo, arg.Name, arg.Created)
	var i ViewerBufo
	err := row.Scan(&i.Name, &i.Created)
	return i, err
}

const createVote = `-- name: CreateVote :one
insert into
    viewer_bufovote (value, created, bufo_id)
values
    (?, ?, ?) returning id, value, created, bufo_id
`

type CreateVoteParams struct {
	Value   int64
	Created time.Time
	BufoID  string
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (ViewerBufovote, error) {
	row := q.db.QueryRowContext(ctx, createVote, arg.Value, arg.Created, arg.BufoID)
	var i ViewerBufovote
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Created,
		&i.BufoID,
	)
	return i, err
}

const getBufo = `-- name: GetBufo :one
select
    name,
    (
        select
            avg(value)
        from
            viewer_bufovote
        where
            bufo_id = name
    ) as rating
from
    viewer_bufo
where
    name = ?
`

type GetBufoRow struct {
	Name   string
	Rating sql.NullFloat64
}

func (q *Queries) GetBufo(ctx context.Context, name string) (GetBufoRow, error) {
	row := q.db.QueryRowContext(ctx, getBufo, name)
	var i GetBufoRow
	err := row.Scan(&i.Name, &i.Rating)
	return i, err
}

const listBufos = `-- name: ListBufos :many
select
    name,
    (
        select
            avg(value)
        from
            viewer_bufovote
        where
            bufo_id = name
    ) as rating
from
    viewer_bufo
`

type ListBufosRow struct {
	Name   string
	Rating sql.NullFloat64
}

func (q *Queries) ListBufos(ctx context.Context) ([]ListBufosRow, error) {
	rows, err := q.db.QueryContext(ctx, listBufos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBufosRow
	for rows.Next() {
		var i ListBufosRow
		if err := rows.Scan(&i.Name, &i.Rating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
