// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbufo

import (
	"time"
)

type ViewerBufo struct {
	Name    string
	Created time.Time
}

type ViewerBufovote struct {
	ID      int64
	Value   int64
	Created time.Time
	BufoID  string
}
